no_new_features_notifications:
  type: bool
  default: true

no_invitee_accepted_notifications:
  type: bool
  default: true

no_membership_accepted_notifications:
  type: bool
  default: true

no_granted_badge_notifications:
  type: bool
  default: true

no_upcoming_change_promoted_notifications:
  type: bool
  default: true

no_review_queue_badges:
  type: bool
  default: true

target_admin_usernames:
  type: string
  default: ""
